// Minimal K230-side updater for the Adafruit/Nordic legacy serial DFU protocol.
//
// This tool intentionally supports application-only packages generated by
// adafruit-nrfutil for the K230 nRF52840 AT firmware. The current package uses
// stored ZIP entries, so no zlib dependency is required on the K230 target.

#include <fcntl.h>
#include <poll.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <termios.h>
#include <unistd.h>

#include <algorithm>
#include <cerrno>
#include <chrono>
#include <string>
#include <thread>
#include <vector>

namespace {

constexpr uint8_t kSlipEnd = 0xC0;
constexpr uint8_t kSlipEsc = 0xDB;
constexpr uint8_t kSlipEscEnd = 0xDC;
constexpr uint8_t kSlipEscEsc = 0xDD;

constexpr uint8_t kDataIntegrity = 1;
constexpr uint8_t kReliablePacket = 1;
constexpr uint8_t kHciPacketType = 14;

constexpr uint32_t kDfuInitPacket = 1;
constexpr uint32_t kDfuStartPacket = 3;
constexpr uint32_t kDfuDataPacket = 4;
constexpr uint32_t kDfuStopDataPacket = 5;
constexpr uint32_t kDfuUpdateModeApp = 4;

constexpr size_t kDefaultDfuPayloadChunk = 32;
constexpr size_t kMaxDfuPayloadChunk = 590;
constexpr int kDefaultBaud = 115200;

struct PackageData {
    std::vector<uint8_t> firmware;
    std::vector<uint8_t> init_packet;
    std::string firmware_name;
    std::string init_name;
};

struct Options {
    std::string port = "/dev/ttyS1";
    std::string package_path;
    std::string at_command;
    int baud = kDefaultBaud;
    int trigger_baud = kDefaultBaud;
    int ack_timeout_ms = 3000;
    int retries = 8;
    int trigger_timeout_ms = 2000;
    int trigger_delay_ms = 3500;
    int at_read_ms = 2000;
    int post_start_delay_ms = 0;
    int post_init_delay_ms = 1000;
    int write_burst_size = 0;
    int write_gap_us = 0;
    int throttle_every = 8;
    int throttle_ms = 120;
    size_t chunk_size = kDefaultDfuPayloadChunk;
    bool trigger = true;
    bool verbose = false;
    bool dry_run = false;
    bool package_version = false;
};

void usage(const char *argv0) {
    fprintf(stderr,
            "Usage: %s [options] <firmware.zip>\n"
            "\n"
            "Options:\n"
            "  -p, --port PATH       UART device. Default: /dev/ttyS1\n"
            "  -b, --baud BAUD       Baud rate. Default: 115200\n"
            "      --trigger-baud BAUD  Baud rate used only for AT+DFU trigger. Default: 115200\n"
            "      --at CMD          Send one AT command, print the response, and exit.\n"
            "      --at-read-ms N    Read window for --at. Default: 2000\n"
            "      --ack-timeout-ms N Wait this long for each DFU ACK. Default: 3000\n"
            "      --retries N        Retry each DFU packet this many times. Default: 8\n"
            "      --trigger-timeout-ms N  Wait for AT+DFU response. Default: 2000\n"
            "      --trigger-delay-ms N    Wait after AT+DFU before DFU packets. Default: 3500\n"
            "      --post-start-delay-ms N Wait after the start packet ACK before init. Default: 0\n"
            "      --post-init-delay-ms N  Wait after the init packet ACK before data. Default: 1000\n"
            "      --chunk-size N     Firmware data payload bytes per packet. Default: 32, max: 590\n"
            "      --write-burst N    Drain the UART after each N encoded bytes. Default: disabled\n"
            "      --write-gap-us N   Delay after each drained write burst. Default: 0\n"
            "      --throttle-every N Sleep after each N DFU data packets. Default: 8, 0 disables.\n"
            "      --throttle-ms N    Sleep duration for --throttle-every. Default: 120\n"
            "      --no-trigger      Do not send AT+DFU before transfer.\n"
            "      --package-version Print the AT firmware version embedded in the package and exit.\n"
            "      --dry-run         Parse package and exit without serial access.\n"
            "  -v, --verbose         Print packet progress details.\n"
            "  -h, --help            Show this help.\n",
            argv0);
}

uint16_t le16(const std::vector<uint8_t> &data, size_t off) {
    return static_cast<uint16_t>(data[off]) |
           (static_cast<uint16_t>(data[off + 1]) << 8);
}

uint32_t le32(const std::vector<uint8_t> &data, size_t off) {
    return static_cast<uint32_t>(data[off]) |
           (static_cast<uint32_t>(data[off + 1]) << 8) |
           (static_cast<uint32_t>(data[off + 2]) << 16) |
           (static_cast<uint32_t>(data[off + 3]) << 24);
}

void append_le16(std::vector<uint8_t> *out, uint16_t value) {
    out->push_back(static_cast<uint8_t>(value & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 8) & 0xff));
}

void append_le32(std::vector<uint8_t> *out, uint32_t value) {
    out->push_back(static_cast<uint8_t>(value & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 8) & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 16) & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 24) & 0xff));
}

bool ends_with(const std::string &value, const char *suffix) {
    const size_t len = strlen(suffix);
    return value.size() >= len &&
           value.compare(value.size() - len, len, suffix) == 0;
}

bool read_file(const std::string &path, std::vector<uint8_t> *out, std::string *err) {
    FILE *fp = fopen(path.c_str(), "rb");
    if (!fp) {
        *err = "failed to open " + path + ": " + strerror(errno);
        return false;
    }
    if (fseek(fp, 0, SEEK_END) != 0) {
        *err = "failed to seek " + path;
        fclose(fp);
        return false;
    }
    const long size = ftell(fp);
    if (size < 0) {
        *err = "failed to tell " + path;
        fclose(fp);
        return false;
    }
    rewind(fp);
    out->resize(static_cast<size_t>(size));
    if (!out->empty() && fread(out->data(), 1, out->size(), fp) != out->size()) {
        *err = "failed to read " + path;
        fclose(fp);
        return false;
    }
    fclose(fp);
    return true;
}

bool parse_stored_zip_package(const std::string &path, PackageData *pkg, std::string *err) {
    std::vector<uint8_t> zip;
    if (!read_file(path, &zip, err)) {
        return false;
    }

    size_t off = 0;
    while (off + 30 <= zip.size()) {
        const uint32_t sig = le32(zip, off);
        if (sig == 0x02014b50 || sig == 0x06054b50) {
            break;
        }
        if (sig != 0x04034b50) {
            *err = "unsupported ZIP layout: missing local file header";
            return false;
        }

        const uint16_t flags = le16(zip, off + 6);
        const uint16_t method = le16(zip, off + 8);
        const uint32_t compressed_size = le32(zip, off + 18);
        const uint32_t uncompressed_size = le32(zip, off + 22);
        const uint16_t name_len = le16(zip, off + 26);
        const uint16_t extra_len = le16(zip, off + 28);
        const size_t name_off = off + 30;
        const size_t data_off = name_off + name_len + extra_len;
        const size_t next = data_off + compressed_size;

        if (name_off + name_len > zip.size() || data_off > zip.size() || next > zip.size()) {
            *err = "truncated ZIP entry";
            return false;
        }
        std::string name(reinterpret_cast<const char *>(&zip[name_off]), name_len);
        if ((flags & 0x0008) != 0) {
            *err = "unsupported ZIP data descriptor entry: " + name;
            return false;
        }
        if (method != 0) {
            *err = "unsupported compressed ZIP entry: " + name;
            return false;
        }
        if (compressed_size != uncompressed_size) {
            *err = "stored ZIP entry size mismatch: " + name;
            return false;
        }

        if (ends_with(name, ".bin")) {
            pkg->firmware.assign(zip.begin() + data_off, zip.begin() + next);
            pkg->firmware_name = name;
        } else if (ends_with(name, ".dat")) {
            pkg->init_packet.assign(zip.begin() + data_off, zip.begin() + next);
            pkg->init_name = name;
        }
        off = next;
    }

    if (pkg->firmware.empty()) {
        *err = "package does not contain an application .bin entry";
        return false;
    }
    if (pkg->init_packet.empty()) {
        *err = "package does not contain an init .dat entry";
        return false;
    }
    return true;
}

bool is_version_char(char ch) {
    return (ch >= '0' && ch <= '9') ||
           (ch >= 'A' && ch <= 'Z') ||
           (ch >= 'a' && ch <= 'z') ||
           ch == '-' || ch == '_' || ch == '.' || ch == '+';
}

bool looks_like_at_version(const std::string &text) {
    if (text.size() < 8 || text.size() > 96) {
        return false;
    }
    if (text.rfind("20", 0) == 0 && text.size() >= 10 &&
        text[4] == '-' && text[7] == '-') {
        return true;
    }
    if (text.find("uart") != std::string::npos ||
        text.find("dfu") != std::string::npos ||
        text.find("k230") != std::string::npos ||
        text.find("K230") != std::string::npos) {
        return true;
    }
    return false;
}

std::string extract_at_package_version(const PackageData &pkg) {
    const std::vector<uint8_t> &data = pkg.firmware;
    std::string best;

    for (size_t i = 0; i < data.size();) {
        while (i < data.size() &&
               (data[i] < 0x20 || data[i] > 0x7e)) {
            i++;
        }
        const size_t start = i;
        while (i < data.size() && data[i] >= 0x20 && data[i] <= 0x7e) {
            i++;
        }
        if (i <= start) {
            continue;
        }
        std::string text(reinterpret_cast<const char *>(&data[start]),
                         i - start);
        size_t pos = text.find("+VER:K230_NRF52840_AT,");
        if (pos != std::string::npos) {
            pos += strlen("+VER:K230_NRF52840_AT,");
            std::string value;
            while (pos < text.size() && is_version_char(text[pos])) {
                value.push_back(text[pos++]);
            }
            if (looks_like_at_version(value)) {
                return value;
            }
        }
        if (looks_like_at_version(text)) {
            if (best.empty() || text.rfind("20", 0) == 0) {
                best = text;
            }
        }
    }
    return best;
}

speed_t baud_to_speed(int baud) {
    switch (baud) {
        case 9600: return B9600;
        case 19200: return B19200;
        case 38400: return B38400;
        case 57600: return B57600;
        case 115200: return B115200;
        case 230400: return B230400;
        case 460800: return B460800;
        case 921600: return B921600;
#ifdef B1000000
        case 1000000: return B1000000;
#endif
        default: return 0;
    }
}

bool configure_serial(int fd, int baud, std::string *err) {
    termios tio {};
    if (tcgetattr(fd, &tio) != 0) {
        *err = std::string("tcgetattr failed: ") + strerror(errno);
        return false;
    }
    cfmakeraw(&tio);
    speed_t speed = baud_to_speed(baud);
    if (speed == 0) {
        *err = "unsupported baud rate";
        return false;
    }
    cfsetispeed(&tio, speed);
    cfsetospeed(&tio, speed);
    tio.c_cflag |= CLOCAL | CREAD;
    tio.c_cflag &= ~CRTSCTS;
    tio.c_cflag &= ~CSTOPB;
    tio.c_cflag &= ~PARENB;
    tio.c_cflag &= ~CSIZE;
    tio.c_cflag |= CS8;
    tio.c_cc[VMIN] = 0;
    tio.c_cc[VTIME] = 1;
    if (tcsetattr(fd, TCSANOW, &tio) != 0) {
        *err = std::string("tcsetattr failed: ") + strerror(errno);
        return false;
    }
    tcflush(fd, TCIOFLUSH);
    return true;
}

int open_serial(const Options &opt, std::string *err) {
    int fd = open(opt.port.c_str(), O_RDWR | O_NOCTTY | O_SYNC);
    if (fd < 0) {
        *err = "failed to open " + opt.port + ": " + strerror(errno);
        return -1;
    }
    if (!configure_serial(fd, opt.baud, err)) {
        close(fd);
        return -1;
    }
    return fd;
}

bool write_all(int fd, const std::vector<uint8_t> &data, std::string *err) {
    size_t off = 0;
    while (off < data.size()) {
        ssize_t n = write(fd, data.data() + off, data.size() - off);
        if (n < 0) {
            if (errno == EINTR) {
                continue;
            }
            *err = std::string("serial write failed: ") + strerror(errno);
            return false;
        }
        off += static_cast<size_t>(n);
    }
    tcdrain(fd);
    return true;
}

bool write_all_throttled(int fd,
                         const std::vector<uint8_t> &data,
                         int burst_size,
                         int gap_us,
                         std::string *err) {
    if (burst_size <= 0 || static_cast<size_t>(burst_size) >= data.size()) {
        return write_all(fd, data, err);
    }

    size_t off = 0;
    while (off < data.size()) {
        const size_t n = std::min(static_cast<size_t>(burst_size), data.size() - off);
        size_t sent = 0;
        while (sent < n) {
            ssize_t wrote = write(fd, data.data() + off + sent, n - sent);
            if (wrote < 0) {
                if (errno == EINTR) {
                    continue;
                }
                *err = std::string("serial write failed: ") + strerror(errno);
                return false;
            }
            sent += static_cast<size_t>(wrote);
        }
        off += n;
        tcdrain(fd);
        if (gap_us > 0 && off < data.size()) {
            std::this_thread::sleep_for(std::chrono::microseconds(gap_us));
        }
    }
    return true;
}

uint16_t crc16_ccitt(uint16_t crc, const std::vector<uint8_t> &data) {
    for (uint8_t b : data) {
        crc = static_cast<uint16_t>(((crc >> 8) & 0x00ff) | ((crc << 8) & 0xff00));
        crc ^= b;
        crc ^= static_cast<uint16_t>((crc & 0x00ff) >> 4);
        crc ^= static_cast<uint16_t>((crc << 8) << 4);
        crc ^= static_cast<uint16_t>(((crc & 0x00ff) << 4) << 1);
    }
    return crc;
}

std::vector<uint8_t> slip_encode(const std::vector<uint8_t> &raw) {
    std::vector<uint8_t> out;
    out.reserve(raw.size() + 8);
    out.push_back(kSlipEnd);
    for (uint8_t b : raw) {
        if (b == kSlipEnd) {
            out.push_back(kSlipEsc);
            out.push_back(kSlipEscEnd);
        } else if (b == kSlipEsc) {
            out.push_back(kSlipEsc);
            out.push_back(kSlipEscEsc);
        } else {
            out.push_back(b);
        }
    }
    out.push_back(kSlipEnd);
    return out;
}

bool slip_decode_frame(const std::vector<uint8_t> &frame, std::vector<uint8_t> *out) {
    out->clear();
    bool esc = false;
    for (uint8_t b : frame) {
        if (esc) {
            if (b == kSlipEscEnd) {
                out->push_back(kSlipEnd);
            } else if (b == kSlipEscEsc) {
                out->push_back(kSlipEsc);
            } else {
                return false;
            }
            esc = false;
        } else if (b == kSlipEsc) {
            esc = true;
        } else {
            out->push_back(b);
        }
    }
    return !esc;
}

std::vector<uint8_t> make_hci_packet(uint8_t seq, const std::vector<uint8_t> &payload) {
    std::vector<uint8_t> raw;
    raw.reserve(4 + payload.size() + 2);
    const uint8_t ack = static_cast<uint8_t>((seq + 1) & 0x07);
    raw.push_back(static_cast<uint8_t>(seq | (ack << 3) |
                                      (kDataIntegrity << 6) |
                                      (kReliablePacket << 7)));
    raw.push_back(static_cast<uint8_t>(kHciPacketType | ((payload.size() & 0x000f) << 4)));
    raw.push_back(static_cast<uint8_t>((payload.size() & 0x0ff0) >> 4));
    raw.push_back(static_cast<uint8_t>((~((raw[0] + raw[1] + raw[2]) & 0xff) + 1) & 0xff));
    raw.insert(raw.end(), payload.begin(), payload.end());
    const uint16_t crc = crc16_ccitt(0xffff, raw);
    append_le16(&raw, crc);
    return slip_encode(raw);
}

bool read_ack(int fd, uint8_t expected_ack, uint8_t *got_ack, int timeout_ms, std::string *err) {
    std::vector<uint8_t> frame;
    bool started = false;
    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);

    while (std::chrono::steady_clock::now() < deadline) {
        const auto now = std::chrono::steady_clock::now();
        const int remain = std::max<int>(1, std::chrono::duration_cast<std::chrono::milliseconds>(deadline - now).count());
        pollfd pfd {fd, POLLIN, 0};
        const int pr = poll(&pfd, 1, remain);
        if (pr < 0) {
            if (errno == EINTR) {
                continue;
            }
            *err = std::string("poll failed: ") + strerror(errno);
            return false;
        }
        if (pr == 0) {
            break;
        }
        uint8_t buf[32];
        const ssize_t n = read(fd, buf, sizeof(buf));
        if (n < 0) {
            if (errno == EINTR) {
                continue;
            }
            *err = std::string("serial read failed: ") + strerror(errno);
            return false;
        }
        for (ssize_t i = 0; i < n; ++i) {
            const uint8_t b = buf[i];
            if (b == kSlipEnd) {
                if (!started) {
                    started = true;
                    frame.clear();
                } else if (!frame.empty()) {
                    std::vector<uint8_t> decoded;
                    if (!slip_decode_frame(frame, &decoded)) {
                        started = false;
                        frame.clear();
                        continue;
                    }
                    if (decoded.size() >= 4) {
                        const uint8_t checksum = static_cast<uint8_t>(decoded[0] + decoded[1] + decoded[2] + decoded[3]);
                        const uint8_t type = decoded[1] & 0x0f;
                        const uint8_t ack = (decoded[0] >> 3) & 0x07;
                        *got_ack = ack;
                        if (checksum == 0 && type == 0 && ack == expected_ack) {
                            return true;
                        }
                    }
                    started = false;
                    frame.clear();
                }
            } else if (started) {
                frame.push_back(b);
                if (frame.size() > 64) {
                    started = false;
                    frame.clear();
                }
            }
        }
    }

    char msg[96];
    snprintf(msg, sizeof(msg), "ack timeout, expected=%u got=%u", expected_ack, *got_ack);
    *err = msg;
    return false;
}

class DfuSender {
public:
    DfuSender(int fd, int ack_timeout_ms, int retries, int write_burst_size, int write_gap_us, bool verbose)
        : fd_(fd),
          ack_timeout_ms_(ack_timeout_ms),
          retries_(retries),
          write_burst_size_(write_burst_size),
          write_gap_us_(write_gap_us),
          verbose_(verbose) {}

    bool send_payload(const std::vector<uint8_t> &payload, const char *label, std::string *err) {
        for (int attempt = 1; attempt <= retries_; ++attempt) {
            const uint8_t expected_ack = static_cast<uint8_t>((seq_ + 1) & 0x07);
            const std::vector<uint8_t> packet = make_hci_packet(seq_, payload);
            if (verbose_) {
                fprintf(stderr, "send %s seq=%u len=%zu attempt=%d\n", label, seq_, payload.size(), attempt);
            }
            if (!write_all_throttled(fd_, packet, write_burst_size_, write_gap_us_, err)) {
                return false;
            }
            uint8_t got_ack = 0xff;
            if (read_ack(fd_, expected_ack, &got_ack, ack_timeout_ms_, err)) {
                seq_ = expected_ack;
                return true;
            }
            if (verbose_) {
                fprintf(stderr, "retry %s: %s\n", label, err->c_str());
            }
        }
        *err = std::string("failed to send ") + label + " after retries";
        return false;
    }

private:
    int fd_;
    int ack_timeout_ms_;
    int retries_;
    int write_burst_size_;
    int write_gap_us_;
    bool verbose_;
    uint8_t seq_ = 1;
};

bool send_at_dfu(const Options &opt, std::string *err) {
    Options trigger_opt = opt;
    trigger_opt.baud = opt.trigger_baud;
    int fd = open_serial(trigger_opt, err);
    if (fd < 0) {
        return false;
    }

    static const char kCmd[] = "AT+DFU\r\n";
    if (write(fd, kCmd, sizeof(kCmd) - 1) != static_cast<ssize_t>(sizeof(kCmd) - 1)) {
        *err = std::string("failed to write AT+DFU: ") + strerror(errno);
        close(fd);
        return false;
    }
    tcdrain(fd);

    char buf[256] {};
    std::string response;
    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(opt.trigger_timeout_ms);
    while (std::chrono::steady_clock::now() < deadline) {
        pollfd pfd {fd, POLLIN, 0};
        int pr = poll(&pfd, 1, 100);
        if (pr > 0) {
            ssize_t n = read(fd, buf, sizeof(buf));
            if (n > 0) {
                response.append(buf, buf + n);
            }
        }
        if (response.find("OK") != std::string::npos ||
            response.find("+DFU:") != std::string::npos) {
            break;
        }
    }
    close(fd);

    if (opt.verbose) {
        if (response.empty()) {
            fprintf(stderr, "AT+DFU response: <none>\n");
        } else {
            fprintf(stderr, "AT+DFU response: %s\n", response.c_str());
        }
    }
    if (response.find("OK") == std::string::npos &&
        response.find("+DFU:") == std::string::npos) {
        *err = "AT+DFU did not return OK/+DFU; nRF52840 AT app may not be running or UART is busy";
        return false;
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(opt.trigger_delay_ms));
    return true;
}

bool send_at_probe(const Options &opt, std::string *err) {
    int fd = open_serial(opt, err);
    if (fd < 0) {
        return false;
    }

    std::string cmd = opt.at_command;
    if (cmd.find('\n') == std::string::npos) {
        cmd += "\r\n";
    }
    if (!write_all(fd, std::vector<uint8_t>(cmd.begin(), cmd.end()), err)) {
        close(fd);
        return false;
    }
    tcdrain(fd);

    std::string response;
    char buf[256] {};
    const auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(opt.at_read_ms);
    while (std::chrono::steady_clock::now() < deadline) {
        const int remain = std::max<int>(1, std::chrono::duration_cast<std::chrono::milliseconds>(deadline - std::chrono::steady_clock::now()).count());
        pollfd pfd {fd, POLLIN, 0};
        const int pr = poll(&pfd, 1, std::min(remain, 200));
        if (pr < 0) {
            if (errno == EINTR) {
                continue;
            }
            *err = std::string("poll failed: ") + strerror(errno);
            close(fd);
            return false;
        }
        if (pr > 0) {
            const ssize_t n = read(fd, buf, sizeof(buf));
            if (n > 0) {
                response.append(buf, buf + n);
            } else if (n < 0 && errno != EINTR) {
                *err = std::string("serial read failed: ") + strerror(errno);
                close(fd);
                return false;
            }
        }
    }
    close(fd);

    if (!response.empty()) {
        fwrite(response.data(), 1, response.size(), stdout);
        if (response.back() != '\n') {
            fputc('\n', stdout);
        }
        return true;
    }
    *err = "no AT response";
    return false;
}

bool send_dfu(const Options &opt, const PackageData &pkg, std::string *err) {
    int fd = open_serial(opt, err);
    if (fd < 0) {
        return false;
    }

    DfuSender sender(fd,
                     opt.ack_timeout_ms,
                     opt.retries,
                     opt.write_burst_size,
                     opt.write_gap_us,
                     opt.verbose);
    const auto transfer_start = std::chrono::steady_clock::now();

    std::vector<uint8_t> start;
    append_le32(&start, kDfuStartPacket);
    append_le32(&start, kDfuUpdateModeApp);
    append_le32(&start, 0);
    append_le32(&start, 0);
    append_le32(&start, static_cast<uint32_t>(pkg.firmware.size()));
    fprintf(stderr, "DFU start: app=%zu bytes init=%zu bytes\n", pkg.firmware.size(), pkg.init_packet.size());
    if (!sender.send_payload(start, "start", err)) {
        close(fd);
        return false;
    }
    if (opt.post_start_delay_ms > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(opt.post_start_delay_ms));
    }

    std::vector<uint8_t> init;
    append_le32(&init, kDfuInitPacket);
    init.insert(init.end(), pkg.init_packet.begin(), pkg.init_packet.end());
    append_le16(&init, 0);
    if (!sender.send_payload(init, "init", err)) {
        close(fd);
        return false;
    }
    if (opt.post_init_delay_ms > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(opt.post_init_delay_ms));
    }

    const size_t total_chunks = (pkg.firmware.size() + opt.chunk_size - 1) / opt.chunk_size;
    const bool progress_tty = isatty(fileno(stderr));
    int last_pct = -1;
    for (size_t off = 0, chunk = 0; off < pkg.firmware.size(); off += opt.chunk_size, ++chunk) {
        const size_t n = std::min(opt.chunk_size, pkg.firmware.size() - off);
        std::vector<uint8_t> data;
        append_le32(&data, kDfuDataPacket);
        data.insert(data.end(), pkg.firmware.begin() + off, pkg.firmware.begin() + off + n);
        if (!sender.send_payload(data, "data", err)) {
            close(fd);
            return false;
        }
        if (opt.throttle_every > 0 && opt.throttle_ms > 0 && ((chunk + 1) % opt.throttle_every) == 0) {
            std::this_thread::sleep_for(std::chrono::milliseconds(opt.throttle_ms));
        }
        const int pct = static_cast<int>(((chunk + 1) * 100) / total_chunks);
        if (pct != last_pct || (chunk + 1) == total_chunks) {
            if (progress_tty) {
                fprintf(stderr, "\rDFU data: %zu/%zu chunks %d%%", chunk + 1, total_chunks, pct);
            } else {
                fprintf(stderr, "DFU data: %zu/%zu chunks %d%%\n", chunk + 1, total_chunks, pct);
            }
            fflush(stderr);
            last_pct = pct;
        }
    }
    if (progress_tty) {
        fprintf(stderr, "\n");
    }

    std::vector<uint8_t> stop;
    append_le32(&stop, kDfuStopDataPacket);
    if (!sender.send_payload(stop, "stop", err)) {
        close(fd);
        return false;
    }

    close(fd);
    fprintf(stderr, "DFU transfer complete, waiting for activation\n");
    std::this_thread::sleep_for(std::chrono::seconds(2));
    const auto transfer_end = std::chrono::steady_clock::now();
    const double elapsed_s = std::chrono::duration<double>(transfer_end - transfer_start).count();
    const double kib_s = elapsed_s > 0.0 ? (static_cast<double>(pkg.firmware.size()) / 1024.0 / elapsed_s) : 0.0;
    fprintf(stderr, "DFU elapsed: %.3fs app-rate: %.2f KiB/s\n", elapsed_s, kib_s);
    return true;
}

bool parse_args(int argc, char **argv, Options *opt) {
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-p" || arg == "--port") {
            if (++i >= argc) {
                return false;
            }
            opt->port = argv[i];
        } else if (arg == "-b" || arg == "--baud") {
            if (++i >= argc) {
                return false;
            }
            opt->baud = atoi(argv[i]);
            if (baud_to_speed(opt->baud) == 0) {
                return false;
            }
        } else if (arg == "--trigger-baud") {
            if (++i >= argc) {
                return false;
            }
            opt->trigger_baud = atoi(argv[i]);
            if (baud_to_speed(opt->trigger_baud) == 0) {
                return false;
            }
        } else if (arg == "--at") {
            if (++i >= argc) {
                return false;
            }
            opt->at_command = argv[i];
        } else if (arg == "--at-read-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->at_read_ms = atoi(argv[i]);
        } else if (arg == "--ack-timeout-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->ack_timeout_ms = atoi(argv[i]);
        } else if (arg == "--retries") {
            if (++i >= argc) {
                return false;
            }
            opt->retries = atoi(argv[i]);
        } else if (arg == "--trigger-timeout-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->trigger_timeout_ms = atoi(argv[i]);
        } else if (arg == "--trigger-delay-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->trigger_delay_ms = atoi(argv[i]);
        } else if (arg == "--post-init-delay-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->post_init_delay_ms = atoi(argv[i]);
        } else if (arg == "--post-start-delay-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->post_start_delay_ms = atoi(argv[i]);
        } else if (arg == "--chunk-size") {
            if (++i >= argc) {
                return false;
            }
            const int value = atoi(argv[i]);
            if (value <= 0 || static_cast<size_t>(value) > kMaxDfuPayloadChunk) {
                return false;
            }
            opt->chunk_size = static_cast<size_t>(value);
        } else if (arg == "--write-burst") {
            if (++i >= argc) {
                return false;
            }
            opt->write_burst_size = atoi(argv[i]);
            if (opt->write_burst_size < 0) {
                return false;
            }
        } else if (arg == "--write-gap-us") {
            if (++i >= argc) {
                return false;
            }
            opt->write_gap_us = atoi(argv[i]);
            if (opt->write_gap_us < 0) {
                return false;
            }
        } else if (arg == "--throttle-every") {
            if (++i >= argc) {
                return false;
            }
            opt->throttle_every = atoi(argv[i]);
            if (opt->throttle_every < 0) {
                return false;
            }
        } else if (arg == "--throttle-ms") {
            if (++i >= argc) {
                return false;
            }
            opt->throttle_ms = atoi(argv[i]);
            if (opt->throttle_ms < 0) {
                return false;
            }
        } else if (arg == "--no-trigger") {
            opt->trigger = false;
        } else if (arg == "--package-version") {
            opt->package_version = true;
        } else if (arg == "--dry-run") {
            opt->dry_run = true;
        } else if (arg == "-v" || arg == "--verbose") {
            opt->verbose = true;
        } else if (arg == "-h" || arg == "--help") {
            usage(argv[0]);
            exit(0);
        } else if (!arg.empty() && arg[0] == '-') {
            return false;
        } else {
            opt->package_path = arg;
        }
    }
    return !opt->package_path.empty() || !opt->at_command.empty();
}

}  // namespace

int main(int argc, char **argv) {
    Options opt;
    if (!parse_args(argc, argv, &opt)) {
        usage(argv[0]);
        return 2;
    }

    if (!opt.at_command.empty()) {
        std::string err;
        if (!send_at_probe(opt, &err)) {
            fprintf(stderr, "at error: %s\n", err.c_str());
            return 1;
        }
        return 0;
    }

    PackageData pkg;
    std::string err;
    if (!parse_stored_zip_package(opt.package_path, &pkg, &err)) {
        fprintf(stderr, "package error: %s\n", err.c_str());
        return 1;
    }
    if (opt.package_version) {
        const std::string version = extract_at_package_version(pkg);
        if (version.empty()) {
            fprintf(stderr, "package version unavailable\n");
            return 1;
        }
        printf("%s\n", version.c_str());
        return 0;
    }
    fprintf(stderr, "Package: bin=%s dat=%s\n", pkg.firmware_name.c_str(), pkg.init_name.c_str());
    fprintf(stderr, "Package sizes: app=%zu init=%zu\n", pkg.firmware.size(), pkg.init_packet.size());
    if (opt.dry_run) {
        fprintf(stderr, "Dry run complete\n");
        return 0;
    }

    if (opt.trigger) {
        fprintf(stderr, "Triggering nRF52840 serial DFU on %s\n", opt.port.c_str());
        if (!send_at_dfu(opt, &err)) {
            fprintf(stderr, "trigger error: %s\n", err.c_str());
            return 1;
        }
    }

    if (!send_dfu(opt, pkg, &err)) {
        fprintf(stderr, "dfu error: %s\n", err.c_str());
        return 1;
    }

    fprintf(stderr, "Done\n");
    return 0;
}
